version : 2.1

jobs:
  build:
    docker:
      - image: cimg/python:3.11
    steps:
      - checkout
      - run: python main.py

  test:
    docker:
      - image: cimg/python:3.11
    steps:
      - checkout
      - run: python tests.py

  deploy:
    docker:
      - image: cimg/python:3.11
    steps:
      - checkout
      - run: echo "deploying webpage to server"

workflows:
  build_and_tests:
    jobs:
      - build
      - test:
          requires:
            - build
      - deploy:
          requires:
            - tests
          filters:
            branches:
              only: main
      